CREATE TABLE ENVELOPES (
    ID UUID NOT NULL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    TYPE VARCHAR(100) NOT NULL,
    BALANCE NUMERIC
);

CREATE TABLE SPENDINGS (
    ID UUID NOT NULL,
    DATE TIMESTAMP NOT NULL,
    ENVELOPE_TYPE VARCHAR(100) NOT NULL,
    AMOUNT NUMERIC
);

CREATE TABLE USERS (
    ID UUID NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    SURNAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(255),
    EMAIL VARCHAR(255) NOT NULL,
    PHONE_NUMBER VARCHAR(255),
    ENVELOPE_ID UUID constraint FK_USERS_ENVELOPE references ENVELOPES,
    INVOICE_ID UUID constraint FK_USERS_INVOICE references SPENDINGS,
);
